language: rust
os: linux
dist: xenial
rust:
  - stable

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/target
    - $HOME/.cargo

before_script:
  - (test -x $HOME/.cargo/bin/wasm-pack || cargo install --vers "^0.9" wasm-pack)

script:
  - cargo test
  - wasm-pack build --release --target web --no-typescript
  - mkdir -p out/pkg
  - cp index.html out/
  - cp -R assets out/
  - mv pkg/units_game* out/pkg/
  - ls -lR out

deploy:
  provider: pages
  strategy: git
  token: $github_token
  edge: true
  cleanup: false
  local_dir: out
  on:
    branch: main